### ISSUE TITLE
ArCH installation

### ISSUE THREAD

**Issue by SoloveyMaria** [kbolton-lab/Archer_Pipeline#8]
Dear developers, 

Thank you for creating this great pipeline! At the moment, the Installation section of the README does not seem to contain the installation instructions. Could you by any chance provide those?

Best,
Maria

**Comment by IrenaeusChan** [comment]
Hello,

Thank you for bringing this to our attention, our README is not currently up-to-date and we will work on updating it as soon as possible. We apologize for the inconvenience and will notify you once this has been completed.

Thank you

**Comment by IrenaeusChan** [comment]
@SoloveyMaria 

Hello, sorry this took a while, we have completed the testing of the installation instructions and have updated the README to reflect this change. Please feel free to follow the README for complete installation and running instructions.
